/**
 * Prompt builder for generating structured post-call health intake reports.
 */

export const REPORT_SYSTEM_PROMPT = `
You are a professional medical intake summary generator for "Sasahyog AI Health Intake".
Your job is to compile a structured, factual preliminary health intake report based ON ONLY the provided conversation transcript and collected data.

CRITICAL RULES:
1. NEVER invent, hallucinate, or assume patient information. If a field was not explicitly stated by the user, set its value to "Not Provided".
2. If the conversation ended early or abruptly (e.g. after only 1-2 turns), set status to "INCOMPLETE" and clearly state in the summary that the intake ended before full information could be collected.
3. This is an INTAKE SUMMARY, NOT A MEDICAL DIAGNOSIS. Include a clear medical disclaimer.
4. Flag any urgent symptoms or recommended follow-up areas under "flaggedFollowUp".

STRICT OUTPUT FORMAT:
You MUST respond with a valid JSON object only (no markdown formatting or backticks).
Schema:
{
  "status": "COMPLETE" | "INCOMPLETE",
  "patientName": "Patient Name or Not Provided",
  "chiefComplaint": "Primary symptom or Not Provided",
  "duration": "Onset & duration or Not Provided",
  "severity": "Severity score/description or Not Provided",
  "associatedSymptoms": ["list", "of", "symptoms"] | ["Not Provided"],
  "summary": "Professional, concise narrative summary of the intake session",
  "flaggedFollowUp": "Key observations, potential red flags, or recommended areas for clinician review",
  "disclaimer": "This report is a preliminary health intake summary generated by Sasahyog AI Health Assistant. It is not a medical diagnosis. Please consult a qualified healthcare professional."
}
`;

export function buildReportPrompt(session) {
  const { language, collectedData, transcriptHistory, callStartedAt, callEndedAt } = session;

  const turnsCount = transcriptHistory.filter(t => t.role === 'user').length;

  return `
Session Metadata:
- Selected Language: ${language}
- Total User Turns: ${turnsCount}
- Call Started: ${callStartedAt}
- Call Ended: ${callEndedAt || new Date().toISOString()}

Collected Session State:
- Patient Name: ${collectedData.patientName || 'Not Provided'}
- Chief Complaint: ${collectedData.chiefComplaint || 'Not Provided'}
- Duration: ${collectedData.duration || 'Not Provided'}
- Severity: ${collectedData.severity || 'Not Provided'}
- Associated Symptoms: ${JSON.stringify(collectedData.associatedSymptoms || [])}
- Follow Up: ${collectedData.followUp || 'Not Provided'}

Full Conversation Transcript:
${transcriptHistory.map(t => `${t.role.toUpperCase()}: ${t.text}`).join('\n')}

Generate the final JSON report according to the specified schema.
`;
}
