import OpenAI from 'openai';
import { config } from '../config/env.js';
import { REPORT_SYSTEM_PROMPT, buildReportPrompt } from '../prompts/reportPrompt.js';

let groqClient = null;
let openaiClient = null;

const GROQ_MODELS = ['groq/compound-mini', 'groq/compound', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b'];

function getOpenAIClient() {
  if (!openaiClient && config.openaiApiKey) {
    openaiClient = new OpenAI({ apiKey: config.openaiApiKey });
  }
  return openaiClient;
}

function getGroqClient() {
  if (!groqClient && config.groqApiKey) {
    groqClient = new OpenAI({
      apiKey: config.groqApiKey,
      baseURL: 'https://api.groq.com/openai/v1',
    });
  }
  return groqClient;
}

/**
 * Generates a structured JSON health intake report from session transcript & data.
 * @param {Object} session - Active session object
 * @returns {Promise<Object>} Structured report object
 */
export async function generateHealthReport(session) {
  const { collectedData, transcriptHistory } = session;
  const userTurns = transcriptHistory.filter(t => t.role === 'user').length;
  const isEarlyCall = userTurns < 2 || !collectedData.chiefComplaint;
  const promptText = buildReportPrompt(session);

  const groq = getGroqClient();
  if (groq) {
    for (const model of GROQ_MODELS) {
      try {
        console.log(`[Report Service (Groq)] Generating report using ${model}...`);
        const completion = await groq.chat.completions.create({
          model: model,
          messages: [
            { role: 'system', content: REPORT_SYSTEM_PROMPT },
            { role: 'user', content: promptText }
          ],
          response_format: { type: 'json_object' },
          temperature: 0.2,
        });

        const rawContent = completion.choices[0]?.message?.content || '{}';
        const report = JSON.parse(rawContent);

        return {
          status: isEarlyCall ? 'INCOMPLETE' : (report.status || 'COMPLETE'),
          patientName: collectedData.patientName || report.patientName || 'Not Provided',
          chiefComplaint: collectedData.chiefComplaint || report.chiefComplaint || 'Not Provided',
          duration: collectedData.duration || report.duration || 'Not Provided',
          severity: collectedData.severity || report.severity || 'Not Provided',
          associatedSymptoms: collectedData.associatedSymptoms?.length > 0
            ? collectedData.associatedSymptoms
            : (Array.isArray(report.associatedSymptoms) && report.associatedSymptoms.length > 0 ? report.associatedSymptoms : ['Not Provided']),
          summary: report.summary || (isEarlyCall
            ? 'The intake call ended before sufficient medical information could be gathered.'
            : 'Preliminary health intake summary recorded.'),
          flaggedFollowUp: report.flaggedFollowUp || 'Routine clinical assessment recommended.',
          disclaimer: 'This report is a preliminary health intake summary generated by Sasahyog AI Health Assistant. It is not a medical diagnosis. Please consult a qualified healthcare professional.'
        };
      } catch (err) {
        console.warn(`[Report Service (Groq ${model}) Warning]:`, err.message);
      }
    }
  }

  // Fallback report generation if offline or error
  return {
    status: isEarlyCall ? 'INCOMPLETE' : 'COMPLETE',
    patientName: collectedData.patientName || 'Not Provided',
    chiefComplaint: collectedData.chiefComplaint || 'Not Provided',
    duration: collectedData.duration || 'Not Provided',
    severity: collectedData.severity || 'Not Provided',
    associatedSymptoms: collectedData.associatedSymptoms?.length > 0 ? collectedData.associatedSymptoms : ['Not Provided'],
    summary: 'Report generated from collected turn data.',
    flaggedFollowUp: 'Consult a medical professional for full evaluation.',
    disclaimer: 'This report is a preliminary health intake summary generated by Sasahyog AI Health Assistant. It is not a medical diagnosis. Please consult a qualified healthcare professional.'
  };
}
