import React from 'react';
import { ShieldAlert, FileText, User, Activity, Clock, AlertTriangle, CheckCircle2, RotateCcw, Printer } from 'lucide-react';

export function HealthReport({ report, onResetCall }) {
  if (!report) return null;

  const isComplete = report.status === 'COMPLETE';

  const printReport = () => {
    window.print();
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-6 glass-panel-glow rounded-3xl space-y-6 animate-fadeIn">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2 text-teal-400 font-bold text-xs tracking-wider uppercase mb-1">
            <FileText className="w-4 h-4" />
            <span>Preliminary Intake Summary</span>
          </div>
          <h2 className="text-2xl font-extrabold text-white">Sasahyog Health Screening Report</h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span
            className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold border ${
              isComplete
                ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
            }`}
          >
            {isComplete ? <CheckCircle2 className="w-3.5 h-3.5" /> : <AlertTriangle className="w-3.5 h-3.5" />}
            <span>{isComplete ? 'INTAKE COMPLETE' : 'INCOMPLETE INTAKE'}</span>
          </span>
        </div>
      </div>

      {/* Medical Safety Disclaimer Alert */}
      <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-200 text-xs flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-bold text-amber-300">PRELIMINARY INTAKE DISCLAIMER: </span>
          {report.disclaimer || 'This report is a preliminary health intake summary generated by Sasahyog AI Health Assistant. It is NOT a medical diagnosis. Please consult a qualified healthcare professional.'}
        </div>
      </div>

      {/* Patient Key Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
        {/* Patient Name */}
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-1">
            <User className="w-3.5 h-3.5 text-teal-400" />
            <span>Patient Name</span>
          </div>
          <p className="text-base font-bold text-slate-100">{report.patientName || 'Not Provided'}</p>
        </div>

        {/* Chief Complaint */}
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-1">
            <Activity className="w-3.5 h-3.5 text-teal-400" />
            <span>Primary Concern</span>
          </div>
          <p className="text-base font-bold text-slate-100">{report.chiefComplaint || 'Not Provided'}</p>
        </div>

        {/* Duration */}
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-1">
            <Clock className="w-3.5 h-3.5 text-teal-400" />
            <span>Onset & Duration</span>
          </div>
          <p className="text-base font-bold text-slate-100">{report.duration || 'Not Provided'}</p>
        </div>

        {/* Severity */}
        <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-1">
            <AlertTriangle className="w-3.5 h-3.5 text-teal-400" />
            <span>Severity</span>
          </div>
          <p className="text-base font-bold text-slate-100">{report.severity || 'Not Provided'}</p>
        </div>
      </div>

      {/* Associated Symptoms */}
      <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Associated Symptoms Reported</h3>
        <div className="flex flex-wrap gap-2 pt-1">
          {Array.isArray(report.associatedSymptoms) && report.associatedSymptoms.length > 0 ? (
            report.associatedSymptoms.map((sym, i) => (
              <span key={i} className="px-3 py-1 rounded-xl bg-teal-500/10 border border-teal-500/20 text-teal-300 text-xs font-medium">
                {sym}
              </span>
            ))
          ) : (
            <span className="text-xs text-slate-500 italic">None reported</span>
          )}
        </div>
      </div>

      {/* Narrative Summary */}
      <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Intake Narrative Summary</h3>
        <p className="text-sm text-slate-200 leading-relaxed font-normal">
          {report.summary || 'Summary unavailable.'}
        </p>
      </div>

      {/* Flagged Follow-up / Red Flags */}
      <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-2">
        <h3 className="text-xs font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
          <AlertTriangle className="w-4 h-4 text-amber-400" />
          <span>Recommended Clinician Follow-up & Observations</span>
        </h3>
        <p className="text-sm text-slate-300 leading-relaxed">
          {report.flaggedFollowUp || 'Routine clinical assessment recommended.'}
        </p>
      </div>

      {/* Action Footer */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-800">
        <button
          type="button"
          onClick={printReport}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2.5 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 text-xs font-semibold rounded-xl transition-all"
        >
          <Printer className="w-4 h-4" />
          <span>Print / Export PDF</span>
        </button>

        <button
          type="button"
          onClick={onResetCall}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-teal-500 hover:bg-teal-400 text-slate-950 text-xs font-bold rounded-xl transition-all shadow-lg shadow-teal-500/20"
        >
          <RotateCcw className="w-4 h-4" />
          <span>Start New Voice Call</span>
        </button>
      </div>
    </div>
  );
}
